# Generated by Django 2.0.1 on 2018-01-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20180125_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='games',
        ),
    ]
