# Generated by Django 2.0.1 on 2018-01-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20180127_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='name',
        ),
    ]
