# Generated by Django 2.0.1 on 2018-01-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_remove_userteam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(default='game.png', upload_to='avatars'),
        ),
    ]
