# Generated by Django 2.0.1 on 2018-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('game', '0002_auto_20180125_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(default=1, on_delete=True, to='match.Match'),
            preserve_default=False,
        ),
    ]
