# Generated by Django 2.0.1 on 2018-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
