# Generated by Django 2.0.1 on 2018-01-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20180128_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turn.Turn'),
        ),
    ]
